### ISSUE TITLE
[Epic]: New JSON/PDF report compatible with CIP High Assurance

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/plutus-testing-tool#5]
### Acknowledgements

- [X] I am a member of the team

### Epic description

The tool shall output a JSON report that allows to easily reach High Assurance as defined by the coming CIP.
New JSON format, readable, usable
New PDF format based on @KJES4's design: https://www.figma.com/file/Bh75uJlkT9lNlgRE0v4gbe/Test-Campaign-PDF-Prototype?type=design&mode=design&t=Umu7G32AFYYCwLHd-0

### Acceptance Criteria/Task List

- [ ] Spec of the new JSON schema compatible with CIP 
- [ ] The tool outputs a JSON that passes the schema
- [ ] PDF is generated

### Priority

Medium

**Comment by KJES4** [comment]
This epic will contain several child stories. At the end of this epic the development team should have a full list of all the information they need to capture from users of the extension so they can generate a test campaign report. The work completed in this epic will consist of the following:
1. Review and finalize the PDF report mockup with PHA team
2. Review work with certification working group
3. Formulate JSON object
4. Develop feature in the extension
